version: '2.1'

services:
  opensourcelabs:
    image: opensourcelabs
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/usr/src/app
    ## set your startup file here
    command: node --inspect app.js