apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: meantodo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: meantodo
    spec:
      containers:
      - name: meantodo
        image: <acr name>.azurecr.io/meantodo
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: "<mongo connection string>"
      imagePullSecrets:
        - name: <acr name>
---
apiVersion: v1
kind: Service
metadata:
  name: meantodo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: meantodo